server:
  servlet:
    context-path: /api/v1.0
  port: 8081

spring:

  jpa:
    database: MYSQL
    hibernate:
      format-sql: true
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_SERVER}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver